version: 0.0
os: linux
files:
  - source: /index.html
    destination: /var/www/html/
hooks:
  BeforeInstall:
    - location: install_dependencies
      timeout: 300
      runas: sudo
    - location: start_server
      timeout: 300
      runas: sudo
  ApplicationStop:
    - location: stop_server
      timeout: 300
      runas: sudo

